name: Hello World
author: Daniel Rodas
description: Some description
inputs:
  who-to-greet:
    description: "Who to greet"
    required: true
    default: Daniel
outputs:
  time:
    description: "The greeting time"
runs:
  using: "docker"
  image: "Dockerfile"
  # entrypoint: 
  args:
    - ${{ inputs.who-to-greet }}